# Generated by Django 4.2.4 on 2023-09-03 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 8, 24, 13, 170180, tzinfo=datetime.timezone.utc)),
        ),
    ]
